services:
  backend:
    container_name: post-backend
    build:
      context: ./backend
      # MODE=[dev | prod] docker compose up -d --build. По умолчанию задан prod
      target: ${MODE:-prod}
    env_file:
      - .env
    ports:
      - 4000:3001
    depends_on:
      db:
        # будет запущен только после того, как сервис db будет считаться здоровым
        condition: service_healthy

  frontend:
    container_name: post-frontend
    build: ./frontend
    ports:
      - 8081:80

  db:
    container_name: postgres
    restart: always
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - db-data:${POSTGRES_PGDATA}
    # healthcheck используется для определения состояния здоровья контейнера
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    ports:
      - 8080:8080

volumes:
  db-data: {}
